Repository UMC-Plan-up/Plan-up-server, pull requests merged in 2025-08, with the labels that each got.

#60 [FEAT] Notification 관련 생성 & 조회 로직
  src/main/java/com/planup/planup/PlanupApplication.java
  src/main/java/com/planup/planup/domain/global/SpringContext.java
  src/main/java/com/planup/planup/domain/goal/entity/Comment.java
  src/main/java/com/planup/planup/domain/goal/entity/Goal.java
  src/main/java/com/planup/planup/domain/goal/service/GoalServiceImpl.java
  src/main/java/com/planup/planup/domain/goal/service/UserGoalServiceImpl.java
  src/main/java/com/planup/planup/domain/notification/controller/NotificationController.java
  src/main/java/com/planup/planup/domain/notification/converter/NotificationConverter.java
  src/main/java/com/planup/planup/domain/notification/dto/NotificationMessageContext.java
  src/main/java/com/planup/planup/domain/notification/dto/NotificationResponseDTO.java
  src/main/java/com/planup/planup/domain/notification/entity/Notification.java
  src/main/java/com/planup/planup/domain/notification/entity/NotificationType.java
  src/main/java/com/planup/planup/domain/notification/entity/TargetType.java
  src/main/java/com/planup/planup/domain/notification/message/NotificationExtraInfo.java
  src/main/java/com/planup/planup/domain/notification/message/NotificationMessageProvider.java
  src/main/java/com/planup/planup/domain/notification/service/NotificationService.java
  src/main/java/com/planup/planup/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/planup/planup/domain/notification/service/NotificationUrlProvider.java
  src/main/java/com/planup/planup/domain/oauth/entity/OAuthAccount.java
  src/main/java/com/planup/planup/domain/report/converter/WeeklyReportResponseConverter.java
  src/main/java/com/planup/planup/domain/report/dto/WeeklyReportResponseDTO.java
  src/main/java/com/planup/planup/domain/report/entity/WeeklyReport.java
  src/main/java/com/planup/planup/domain/report/service/WeeklyReportServiceImpl.java
  src/main/java/com/planup/planup/domain/user/entity/User.java
  src/main/java/com/planup/planup/domain/user/service/UserServiceImpl.java
Labels: ✨FEAT

#66 [FIX] 친구 리스트 조회 시 goalCnt, todayTime, isNewPhotoVerify 실제 데이터 구현 및 중복 제거
  src/main/java/com/planup/planup/domain/friend/converter/FriendConverter.java
  src/main/java/com/planup/planup/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/planup/planup/domain/verification/repository/PhotoVerificationRepository.java
Labels: ✨FEAT

#64 [FEAT] 회원가입 시 이메일 본인 인증 구현
  build.gradle
  src/main/java/com/planup/planup/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/planup/planup/domain/user/controller/UserController.java
  src/main/java/com/planup/planup/domain/user/dto/EmailSendResponseDTO.java
  src/main/java/com/planup/planup/domain/user/dto/EmailVerificationRequestDTO.java
  src/main/java/com/planup/planup/domain/user/dto/EmailVerificationResponseDTO.java
  src/main/java/com/planup/planup/domain/user/dto/EmailVerifyLinkResponseDTO.java
  src/main/java/com/planup/planup/domain/user/dto/EmailVerifyTokenRequestDTO.java
  src/main/java/com/planup/planup/domain/user/dto/ResendEmailRequestDTO.java
  src/main/java/com/planup/planup/domain/user/entity/User.java
  src/main/java/com/planup/planup/domain/user/service/EmailService.java
  src/main/java/com/planup/planup/domain/user/service/EmailServiceImpl.java
  src/main/java/com/planup/planup/domain/user/service/UserService.java
  src/main/java/com/planup/planup/domain/user/service/UserServiceImpl.java
  src/main/resources/application.yml
Labels: ✨FEAT

#72 [FIX] 이메일 중복 확인 로직 수정
  src/main/java/com/planup/planup/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/planup/planup/domain/user/controller/UserController.java
  src/main/java/com/planup/planup/domain/user/dto/WithdrawalRequestDTO.java
  src/main/java/com/planup/planup/domain/user/dto/WithdrawalResponseDTO.java
  src/main/java/com/planup/planup/domain/user/service/UserServiceImpl.java
Labels: ♻️ refactor

#86 [REF] goal에 비활성화 버튼 생성 및 리펙토링
  build/resources/main/application.yml
  src/main/java/com/planup/planup/domain/friend/converter/FriendConverter.java
  src/main/java/com/planup/planup/domain/friend/service/FriendService.java
  src/main/java/com/planup/planup/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/planup/planup/domain/global/scheduler/GoalExpireScheduler.java
  src/main/java/com/planup/planup/domain/goal/entity/Goal.java
  src/main/java/com/planup/planup/domain/goal/entity/mapping/UserGoal.java
  src/main/java/com/planup/planup/domain/goal/repository/GoalRepository.java
  src/main/java/com/planup/planup/domain/goal/repository/UserGoalRepository.java
  src/main/java/com/planup/planup/domain/goal/service/ChallengeServiceImpl.java
  src/main/java/com/planup/planup/domain/goal/service/CommentServiceImpl.java
  src/main/java/com/planup/planup/domain/goal/service/GoalLifeService.java
  src/main/java/com/planup/planup/domain/goal/service/GoalService.java
  src/main/java/com/planup/planup/domain/goal/service/GoalServiceImpl.java
  src/main/java/com/planup/planup/domain/goal/service/UserGoalService.java
  src/main/java/com/planup/planup/domain/goal/service/UserGoalServiceImpl.java
  src/main/java/com/planup/planup/domain/report/service/GoalReportServiceImpl.java
  src/main/java/com/planup/planup/domain/report/service/WeeklyReportServiceImpl.java
  src/main/java/com/planup/planup/domain/verification/controller/VerificationController.java
  src/main/java/com/planup/planup/domain/verification/service/PhotoVerificationReadService.java
  src/main/java/com/planup/planup/domain/verification/service/PhotoVerificationService.java
  src/main/java/com/planup/planup/domain/verification/service/TimerVerificationReadService.java
  src/main/java/com/planup/planup/domain/verification/service/TimerVerificationService.java
  src/main/java/com/planup/planup/domain/verification/service/VerificationService.java
Labels: ♻️ refactor

#90 [FEAT] 로그인 에러 메시지 응답 추가
  src/main/java/com/planup/planup/apiPayload/exception/custom/UserException.java
  src/main/java/com/planup/planup/domain/user/dto/LoginResponseDTO.java
  src/main/java/com/planup/planup/domain/user/service/UserServiceImpl.java
Labels: ✨FEAT

#84 [FEAT] challenge의 결과를 조회하는 메서드 생성
  .github/workflows/dev_deploy.yml
  build/resources/main/application.yml
  src/main/java/com/planup/planup/domain/global/service/AchievementCalculationService.java
  src/main/java/com/planup/planup/domain/goal/controller/ChallengeController.java
  src/main/java/com/planup/planup/domain/goal/dto/ChallengeResponseDTO.java
  src/main/java/com/planup/planup/domain/goal/entity/Goal.java
  src/main/java/com/planup/planup/domain/goal/entity/mapping/UserGoal.java
  src/main/java/com/planup/planup/domain/goal/service/ChallengeService.java
  src/main/java/com/planup/planup/domain/goal/service/ChallengeServiceImpl.java
  src/main/java/com/planup/planup/domain/goal/service/GoalLifeService.java
  src/main/java/com/planup/planup/domain/notification/service/NotificationCreateService.java
  src/main/java/com/planup/planup/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/planup/planup/domain/report/service/GoalReportServiceImpl.java
  src/main/java/com/planup/planup/domain/verification/repository/PhotoVerificationRepository.java
  src/main/java/com/planup/planup/domain/verification/repository/TimerVerificationRepository.java
  src/main/java/com/planup/planup/domain/verification/service/PhotoVerificationReadService.java
  src/main/java/com/planup/planup/domain/verification/service/PhotoVerificationService.java
  src/main/java/com/planup/planup/domain/verification/service/TimerVerificationReadService.java
  src/main/java/com/planup/planup/domain/verification/service/TimerVerificationService.java
Labels: ✨FEAT

#100 [FEAT] 프로필 설정 시 랜덤 닉네임 제공 API 구현
  src/main/java/com/planup/planup/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/planup/planup/domain/user/controller/UserController.java
  src/main/java/com/planup/planup/domain/user/dto/RandomNicknameResponseDTO.java
  src/main/java/com/planup/planup/domain/user/entity/Adjective.java
  src/main/java/com/planup/planup/domain/user/entity/Noun.java
  src/main/java/com/planup/planup/domain/user/entity/RandomNickname.java
  src/main/java/com/planup/planup/domain/user/repository/AdjectiveRepository.java
  src/main/java/com/planup/planup/domain/user/repository/NounRepository.java
  src/main/java/com/planup/planup/domain/user/service/RandomNicknameService.java
  src/main/java/com/planup/planup/domain/user/service/RandomNicknameServiceImpl.java
Labels: ✨FEAT

#108 [FEAT] 이메일 중복 확인 API 추가
  src/main/java/com/planup/planup/domain/user/controller/UserController.java
  src/main/java/com/planup/planup/domain/user/dto/EmailDuplicateResponseDTO.java
  src/main/java/com/planup/planup/domain/user/service/UserService.java
  src/main/java/com/planup/planup/domain/user/service/UserServiceImpl.java
Labels: ✨FEAT

#120 [FEAT] challenge에 notificaion 추가, 에러 메세지 추가
  src/main/java/com/planup/planup/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/planup/planup/domain/goal/controller/ChallengeController.java
  src/main/java/com/planup/planup/domain/goal/controller/GoalController.java
  src/main/java/com/planup/planup/domain/goal/convertor/CommentConverter.java
  src/main/java/com/planup/planup/domain/goal/entity/Comment.java
  src/main/java/com/planup/planup/domain/goal/service/ChallengeService.java
  src/main/java/com/planup/planup/domain/goal/service/ChallengeServiceImpl.java
  src/main/java/com/planup/planup/domain/goal/service/CommentService.java
  src/main/java/com/planup/planup/domain/goal/service/CommentServiceImpl.java
  src/main/java/com/planup/planup/domain/goal/service/GoalService.java
  src/main/java/com/planup/planup/domain/goal/service/GoalServiceImpl.java
  src/main/java/com/planup/planup/domain/notification/message/NotificationMessageProvider.java
  src/main/java/com/planup/planup/domain/notification/service/NotificationCreateService.java
  src/main/java/com/planup/planup/domain/report/controller/GoalReportController.java
  src/main/java/com/planup/planup/domain/report/converter/GoalReportConverter.java
  src/main/java/com/planup/planup/domain/report/dto/GoalReportResponseDTO.java
  src/main/java/com/planup/planup/domain/report/entity/GoalReport.java
  src/main/java/com/planup/planup/domain/report/service/GoalReportService.java
  src/main/java/com/planup/planup/domain/report/service/GoalReportServiceImpl.java
Labels: ♻️ refactor

#125 [Fix] 초대코드 사용 완료 처리 로직 수정
  src/main/java/com/planup/planup/domain/user/service/InviteCodeService.java
  src/main/java/com/planup/planup/domain/user/service/UserServiceImpl.java
Labels: ♻️ refactor

#143 [FIX] 프로필 이미지 업로드 API에서 JWT 인증 삭제
  src/main/java/com/planup/planup/config/SecurityConfig.java
  src/main/java/com/planup/planup/domain/user/controller/UserController.java
  src/main/java/com/planup/planup/domain/user/service/UserService.java
  src/main/java/com/planup/planup/domain/user/service/UserServiceImpl.java
  src/main/java/com/planup/planup/validation/jwt/JwtAuthenticationFilter.java
Labels: 🐜bug
